import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// 'Geist'와 'Geist_Mono' 폰트를 next/font/local을 사용하여 불러옵니다.
// src 경로를 프로젝트 내의 실제 폰트 파일 경로로 수정해야 합니다.
const geistSans = localFont({
  src: "../assets/fonts/Geist-Variable.woff2", // 이 경로를 실제 폰트 파일 경로로 변경하세요.
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "../assets/fonts/GeistMono-Variable.woff2", // 이 경로를 실제 폰트 파일 경로로 변경하세요.
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
